---
## Verify nftables Service is Disabled
- name: Gather the package facts
  package_facts:
    manager: auto

- name:
    Verify nftables Service is Disabled - Collect systemd Services Present in
    the System
  ansible.builtin.command: systemctl -q list-unit-files --type service
  register: service_exists
  changed_when: false
  failed_when: service_exists.rc not in [0, 1]
  check_mode: false
  when:
    ( "firewalld" in ansible_facts.packages and "nftables" in ansible_facts.packages
    and "kernel" in ansible_facts.packages )

- name: Verify nftables Service is Disabled - Ensure nftables.service is Masked
  ansible.builtin.systemd:
    name: nftables.service
    state: stopped
    enabled: false
    masked: true
  when:
    - ( "firewalld" in ansible_facts.packages and "nftables" in ansible_facts.packages
      and "kernel" in ansible_facts.packages )
    - service_exists.stdout_lines is search("nftables.service", multiline=True)

- name: Unit Socket Exists - nftables.socket
  ansible.builtin.command: systemctl -q list-unit-files nftables.socket
  register: socket_file_exists
  changed_when: false
  failed_when: socket_file_exists.rc not in [0, 1]
  check_mode: false
  when:
    ( "firewalld" in ansible_facts.packages and "nftables" in ansible_facts.packages
    and "kernel" in ansible_facts.packages )

- name: Verify nftables Service is Disabled - Disable Socket nftables
  ansible.builtin.systemd:
    name: nftables.socket
    enabled: false
    state: stopped
    masked: true
  when:
    - ( "firewalld" in ansible_facts.packages and "nftables" in ansible_facts.packages
      and "kernel" in ansible_facts.packages )
    - socket_file_exists.stdout_lines is search("nftables.socket", multiline=True)

# Disable systemd-journal-remote Socket
- name: Gather the package facts
  package_facts:
    manager: auto

- name:
    Disable systemd-journal-remote Socket - Collect systemd Socket Units Present
    in the System
  ansible.builtin.command:
    cmd: systemctl -q list-unit-files --type socket
  register: result_systemd_unit_files
  changed_when: false
  when: '"kernel" in ansible_facts.packages'

- name:
    Disable systemd-journal-remote Socket - Ensure systemd-journal-remote.socket
    is Masked
  ansible.builtin.systemd:
    name: systemd-journal-remote.socket
    state: stopped
    enabled: false
    masked: true
  when:
    - '"kernel" in ansible_facts.packages'
    - result_systemd_unit_files.stdout_lines is search("systemd-journal-remote.socket")
